
### 取得 token client_credentials flow
POST https://localhost:5001/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=console&client_secret=388D45FA-B36B-4988-BA59-B187D329C207

### 取用資源 API
GET http://localhost:5002/api/Values
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkM2QkQ1OEE2QUYwMEEwMEZBREFEOTAyQkMzNzY1NDRDQkFBOTUzNDkiLCJ4NXQiOiJ4cjFZcHE4QW9BLXRyWkFydzNaVVRMcXBVMGsiLCJ0eXAiOiJhdCtqd3QifQ.eyJzdWIiOiJjb25zb2xlIiwibmFtZSI6Ik15IGNsaWVudCBhcHBsaWNhdGlvbiIsIm9pX3Byc3QiOiJjb25zb2xlIiwiY2xpZW50X2lkIjoiY29uc29sZSIsIm9pX3Rrbl9pZCI6Ijg3NTY0MzdlLTUzOTgtNGM4MC1hNDc3LTY0MWFhODQ0YzQ5OSIsImV4cCI6MTYxMzIwNDM3MiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMS8iLCJpYXQiOjE2MTMyMDA3NzJ9.KrW7p6olXQMkbGVDF8wWEhNWfevz5yMcqwzH52LWKfQQmLFsdWCJEi74U5Iue3Lspxv2zBwXc-uTKyXafSurCraqlSing2XSFvQVtS2CtzrxR699paXYmGsOQ26-vio5p45l7fBhT8MbhFBQG1BWYIi8GtuqCEBxooTcaAz2XzgrVXKiJWG8z64YkJD-vMe_1FFIGaGl83XS_8DxhZYtQSz5fV_A0sHZItsOWm4W0UNo964cNomTljQBdoE2r8VgirHhgNXwcy9MOnXgkYnV0g4yN1JJmr7HLvQjO2ogIY5IUlnztYIEKTc8biYiU8z9Mdu_OFJHR70K96bEwKZtEQ