
### 取得 token client_credentials flow
POST https://localhost:5001/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=console&client_secret=388D45FA-B36B-4988-BA59-B187D329C207

### 取用資源 API
GET http://localhost:5002/api/Values
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkM2QkQ1OEE2QUYwMEEwMEZBREFEOTAyQkMzNzY1NDRDQkFBOTUzNDkiLCJ4NXQiOiJ4cjFZcHE4QW9BLXRyWkFydzNaVVRMcXBVMGsiLCJ0eXAiOiJhdCtqd3QifQ.eyJzdWIiOiJjb25zb2xlIiwibmFtZSI6Ik15IGNsaWVudCBhcHBsaWNhdGlvbiIsIm9pX3Byc3QiOiJjb25zb2xlIiwiY2xpZW50X2lkIjoiY29uc29sZSIsIm9pX3Rrbl9pZCI6IjI3M2ViMWZiLTk0ZjUtNGYwNi04ZmQyLTllYzdjZjU1ZWU4ZiIsImV4cCI6MTYxMzIxNzY2MywiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMS8iLCJpYXQiOjE2MTMyMTQwNjN9.YNPLhjAHBaIEoWhaCY4cZ65ZIYCU_cuibZ2_U7MHHNi7i7BTpvrY3t7SvU-efiO08YxfK8wCfK3hnaAHlJxjsaFk8rJ1x7hjtcHkoxYq1XAFdkX29V0Z6IIzHWNmmK3W8MYKeaf1noMuOqoaDLy-dUgNRv6iqWeo5ONctPf-aJsrcHnOicvl2-uYBwBGmsZsE6aaXYJ45nAkaeqOioFoLc_5W90JbFvxaybALaLqIA3NKuQZrmQxkg5Bg_D_qarQytKtiF8SDsVOzroirLA_aVApp4NjEE7aq8UjHUnDgc5Dk1DbC4LDbW4U7AHMKWVWJl1C-JX6m09p1T_fOzA-IQ